name: pcpn_server
version: 1.0.0

dependencies:
  mysql_client: ^0.0.27
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3

dev_dependencies:
  test: ^1.16.0
  flutter_lints: ^4.0.0

environment:
  sdk: ^3.5.3